name = "Cliff"
uuid = "5e6218ff-0000-0000-0000-000000000000"
authors = ["Cliff.jl Contributors"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
PrecompileTools = "1.3.3"
julia = "1.9"
